using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TuneOrBuy.Services.Cars.Enums
{
    public enum Manufactures
    {
        VW = 1,
        MercedesBenz = 2,
        BMW = 3,
        Audi = 4,
        Opel = 5,
        Peugeot = 6,
        Toyota = 7,
        Renault = 8,
        Ford = 9,
        Citroen = 10,
        Nissan = 11,
        Honda = 12,
        Mazda = 13,
        Fiat = 14,
        Skoda = 15,
        Hyundai = 16,
        Seat = 17,
        Kia = 18,
        Mitsubishi = 19,
        Suzuki = 20,
        Volvo = 21,
        Subaru = 22,
        Dacia = 23,
        AlfaRomeo = 24,
        Chevrolet = 25,
        LandRover = 26,
        Jeep = 27,
        Mini = 28,
        Lancia = 29,
        Daihatsu = 30,
        Chrysler = 31,
        Porsche = 32,
        Ssangyong = 33,
        Smart = 34,
        Jaguar = 35,
        Lada = 36,
        Lexus = 37,
        Rover = 38,
        Saab = 39,
        Daewoo = 40,
        Dodge = 41,
        Infiniti = 42,
        Tesla = 43,
        Isuzu = 44,
        Greatwall = 45,
        RangeRover = 46,
        UAZ = 47,
        Cadillac = 48,
        Moskvich = 49,
        Tata = 50,
        DS = 51,
        Trabant = 52,
        Maserati = 53,
        Wartburg = 54,
        Lincoln = 55,
        DR = 56,
        MG = 57,
        Volga = 58,
        GAZ = 59,
        Bentley = 60,
        Acura = 61,
        Pontiac = 62,
        Hummer = 63,
        ВАЗ = 64,
        AstonMartin = 65,
        Haval = 66,
        Zaz = 67,
        Mahindra = 68,
        RollsRoyce = 69,
        GMC = 70,
        Ferrari = 71,
        Варшава = 72,
        Lamborghini = 73,
        Buick = 74,
        Iveco = 75,
        Simca = 76,
        Zastava = 77,
        DFSK = 78,
        Aro = 79,
        Yogomo = 80,
        Microcar = 81,
        Datsun = 82,
        Tempo = 83,
        AsiaMotors = 84,
        LDV = 85,
        Maybach = 86,
        Landwind = 87,
        Excalibur = 88,
        Triumph = 89,
        Cupra = 90,
        BYD = 91,
        GacGonow = 92,
        Oldsmobile = 93,
        Barkas = 94,
        Piaggio = 95,
        Geo = 96,
        Talbot = 97,
        Lotus = 98,
        Brilliance = 99,
        Austin = 100,
        McLaren = 101,
        Scion = 102,
    }
}
