namespace TuneOrBuy.Web.Models.Car
{
    public class CarConstants
    {
        public static List<string> Manufacturers = new List<string>()
        {
            "Acura",
            "AlfaRomeo",
            "Aro",
            "AsiaMotors",
            "AstonMartin",
            "Audi",
            "Austin",
            "Barkas",
            "Bentley",
            "BMW",
            "Brilliance",
            "Buick",
            "BYD",
            "Cadillac",
            "Chevrolet",
            "Chrysler",
            "Citroen",
            "Cupra",
            "Dacia",
            "Daewoo",
            "Daihatsu",
            "Datsun",
            "DFSK",
            "Dodge",
            "DR",
            "DS",
            "Excalibur",
            "Ferrari",
            "Fiat",
            "Ford",
            "GacGonow",
            "GAZ",
            "Geo",
            "GMC",
            "Greatwall",
            "Haval",
            "Honda",
            "Hummer",
            "Hyundai",
            "Infiniti",
            "Isuzu",
            "Iveco",
            "Jaguar",
            "Jeep",
            "Kia",
            "Lada",
            "Lamborghini",
            "Lancia",
            "LandRover",
            "Landwind",
            "LDV",
            "Lexus",
            "Lincoln",
            "Lotus",
            "Mahindra",
            "Maserati",
            "Maybach",
            "Mazda",
            "McLaren",
            "MercedesBenz",
            "MG",
            "Microcar",
            "Mini",
            "Mitsubishi",
            "Moskvich",
            "Nissan",
            "Oldsmobile",
            "Opel",
            "Peugeot",
            "Piaggio",
            "Pontiac",
            "Porsche",
            "RangeRover",
            "Renault",
            "RollsRoyce",
            "Rover",
            "Saab",
            "Scion",
            "Seat",
            "Simca",
            "Skoda",
            "Smart",
            "Ssangyong",
            "Subaru",
            "Suzuki",
            "Talbot",
            "Tata",
            "Tempo",
            "Tesla",
            "Toyota",
            "Trabant",
            "Triumph",
            "UAZ",
            "Volga",
            "Volvo",
            "VW",
            "Wartburg",
            "Yogomo",
            "Zastava",
            "Zaz",
            "ВАЗ",
            "Варшава"
        };

        public static List<string> BodyTypes = new List<string>()
        {
            "Coupe",
            "Sedan",
            "Hatchback",
            "StationWagon",
            "Convertible",
            "SUV",
            "PickUp",
            "Van"
        };

        public static List<string> FuelType = new List<string>()
        {
            "Gasoline",
            "Diesel",
            "LPG",
            "Hybrid",
            "Electricity"
        };

        public static List<string> GearTypes = new List<string>()
        {
            "Manual",
            "Automatic"
        };

        public static List<string> NumberOfDoors = new List<string>()
        {
            "2/3",
            "4/5"
        };

        public static List<string> NumberOfSeats = new List<string>()
        {
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9"
        };

        public static List<string> EquipmentsToChooseFrom = new List<string>()
        {
            "360° camera",
            "4WD",
            "ABS",
            "Adaptive Cruise Control",
            "Adaptive headlights",
            "Air conditioning",
            "Air suspension",
            "Alarm system",
            "All season tyres",
            "Alloy wheels",
            "Ambient lighting",
            "Android Auto",
            "Apple CarPlay",
            "Armrest",
            "Automatic climate control",
            "Automatic climate control, 2 zones",
            "Automatic climate control, 3 zones",
            "Automatic climate control, 4 zones",
            "Automatically dimming interior mirror",
            "Auxiliary heating",
            "Awning",
            "Bi-Xenon headlights",
            "Biodiesel conversion",
            "Blind spot monitor",
            "Bluetooth",
            "Cab or rented Car",
            "Cargo barrier",
            "Catalytic Converter",
            "CD player",
            "Central door lock",
            "Central door lock with remote control",
            "Cruise control",
            "Daytime running lights",
            "Digital cockpit",
            "Digital radio",
            "Disabled accessible",
            "Distance warning system",
            "Driver drowsiness detection",
            "Driver-side airbag",
            "E10-enabled",
            "Electric backseat adjustment",
            "Electric tailgate",
            "Electrical side mirrors",
            "Electrically adjustable seats",
            "Electrically heated windshield",
            "Electronic parking brake",
            "Electronic stability control",
            "Emergency brake assistant",
            "Emergency system",
            "Emergency tyre",
            "Emergency tyre repair kit",
            "Fog lights",
            "Fold flat passenger seat",
            "Full-LED headlights",
            "Glare-free high beam headlights",
            "Hands-free equipment",
            "Head airbag",
            "Headlight washer system",
            "Heads-up display",
            "Heated steering wheel",
            "High beam assist",
            "Hill Holder",
            "Immobilizer",
            "Induction charging for smartphones",
            "Integrated music streaming",
            "Isofix",
            "Keyless central door lock",
            "Lane departure warning system",
            "Laser headlights",
            "Leather seats",
            "Leather steering wheel",
            "LED Daytime Running Lights",
            "LED Headlights",
            "Light sensor",
            "Lumbar support",
            "Massage seats",
            "MP3",
            "Multi-function steering wheel",
            "Navigation system",
            "Night view assist",
            "On-board computer",
            "Panorama roof",
            "Park Distance Control",
            "Parking assist system camera",
            "Parking assist system self-steering",
            "Parking assist system sensors front",
            "Parking assist system sensors rear",
            "Passenger-side airbag",
            "Power steering",
            "Power windows",
            "Radio",
            "Rain sensor",
            "Range extender",
            "Rear airbag",
            "Right-hand drive",
            "Roof rack",
            "Seat heating",
            "Seat ventilation",
            "Shift paddles",
            "Side airbag",
            "Ski bag",
            "Sliding door",
            "Sliding door left",
            "Sliding door right",
            "Smoker's package",
            "Sound system",
            "Spare tyre",
            "Speed limit control system",
            "Split rear seats",
            "Spoiler",
            "Sport package",
            "Sport seats",
            "Sport suspension",
            "Start-stop system",
            "Steel wheels",
            "Summer tyres",
            "Sunroof",
            "Television",
            "Tinted windows",
            "Tire pressure monitoring system",
            "Touch screen",
            "Traction control",
            "Traffic sign recognition",
            "Trailer hitch",
            "Tuned car",
            "USB",
            "Voice Control",
            "Wind deflector",
            "Winter package",
            "Winter tyres",
            "WLAN / WiFi hotspot"
        };
    }
}
